version: "3.9"
services:
  timescale:
    image: timescale/timescaledb:2.4.2-pg12
    ports:
      - "5432:5432"
    volumes:
      - "timescale-data:/var/lib/postgresql/data"
volumes:
  "timescale-data": {}
