#!/usr/bin/env bash

set -eu

file=$1

workers=$(getconf _NPROCESSORS_ONLN)

echo "using $workers workers"

timescaledb-parallel-copy \
  --connection "host=localhost user=test sslmode=disable port=5433 password=test" \
  --db-name test \
  --table rides \
  --file $file \
  --workers $workers \
  --truncate \
  --reporting-period 30s
